services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: admin
      MYSQL_PASSWORD: H0l4mund0!
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql